FROM python:3.9-slim

WORKDIR /app

COPY async_proxy.py /app/proxy.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt \
    && pip install hypercorn

CMD ["hypercorn", "proxy:app", "--bind", "0.0.0.0:80", "--workers", "6"]