apiVersion: v1
kind: Service
metadata:
  name: proxy-${BACKEND_NAME}
  labels:
    app: pattern
spec:
  selector:
    app: ${DEPLOYMENT_NAME}
  ports:
    - protocol: TCP
      port: ${BACKEND_PORT}
      targetPort: 80
  type: ClusterIP