apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel
  labels:
    app: otel-collector
spec:
  ports:
  - name: otlp # Default endpoint for OpenTelemetry receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: jaeger-grpc # Default endpoint for Jaeger gRPC receiver
    port: 14250
  - name: jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
    port: 14268
  - name: prom-metrics
    port: 9464
    targetPort: 9464 # Prometheus metrics (spanmetrics)
  selector:
    app: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.122.1
        args: ["--config=/etc/otel/config.yaml"]
        ports:
          - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
          - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
          - containerPort: 4317 # OTLP gRPC
          - containerPort: 4318 # OTLP HTTP
          - containerPort: 9464 # Prometheus metrics (spanmetrics)
        volumeMounts:
          - name: config
            mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
