apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-aggregation-config
  namespace: pattern
data:
  SERVICE_1_NAME: "teastore-product"
  SERVICE_1_ENDPOINT: "/products"
  SERVICE_1_HOST: "teastore-webui.user.svc.cluster.local"
  SERVICE_1_PORT: "8080"
  
  SERVICE_2_NAME: "teastore-image"
  SERVICE_2_ENDPOINT: "/images"
  SERVICE_2_HOST: "teastore-image.user.svc.cluster.local"
  SERVICE_2_PORT: "8080"

  SERVICE_3_NAME: "teastore-recommender"
  SERVICE_3_ENDPOINT: "/recommendations"
  SERVICE_3_HOST: "teastore-recommender.user.svc.cluster.local"
  SERVICE_3_PORT: "8080"