apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-aggregation-config
  namespace: pattern
data:
  SERVICE_1_NAME: "${SERVICE_1_NAME}"
  SERVICE_1_PATH: "${SERVICE_1_PATH}"
  SERVICE_1_HOST: "${SERVICE_1_HOST}"
  SERVICE_1_PORT: "${SERVICE_1_PORT}"

  SERVICE_2_NAME: "${SERVICE_2_NAME}"
  SERVICE_2_PATH: "${SERVICE_2_PATH}"
  SERVICE_2_HOST: "${SERVICE_2_HOST}"
  SERVICE_2_PORT: "${SERVICE_2_PORT}"

  SERVICE_3_NAME: "${SERVICE_3_NAME}"
  SERVICE_3_PATH: "${SERVICE_3_PATH}"
  SERVICE_3_HOST: "${SERVICE_3_HOST}"
  SERVICE_3_PORT: "${SERVICE_3_PORT}"