apiVersion: v1
kind: Service
metadata:
  labels:
    app: pattern
  name: cache-proxy-${BACKEND_SERVICE}
  namespace: pattern
spec:
  selector:
    app: cache-proxy-${BACKEND_SERVICE}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80