apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-service
  namespace: pattern
  labels:
    app: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-service
  template:
    metadata:
      labels:
        app: batch-service
      annotations:
        instrumentation.opentelemetry.io/inject-python: "otel/otel-operator-instrumentation"
    spec:
      containers:
        - name: batch-proxy-service-container
          image: batch-proxy-service:local
          env:
            - name: DB_HOST
              value: "${DB_HOST}"     # teastore-db-backend.user.svc.cluster.local
            - name: DB_PORT
              value: "${DB_PORT}"     # 3306
            - name: DB_NAME
              value: "${DB_NAME}"     # TeaStoreDB
            - name: DB_USER
              value: "${DB_USER}"     # teauser
            - name: DB_PASS
              value: "${DB_PASS}"     # teapassword
            - name: BATCH_QUERY
              value: "${BATCH_QUERY}" # SELECT id, name, description FROM Product WHERE id IN (%s)
            - name: QUERY_PARAM
              value: "${QUERY_PARAM}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: batch-service
  namespace: pattern
  labels:
    app: pattern
spec:
  selector:
    app: batch-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP