apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cache-routing
  namespace: pattern
spec:
  hosts:
    - teastore-persistence.user.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /tools.descartes.teastore.persistence/rest/products
      route:
        - destination:
            host: proxy-cache.pattern.svc.cluster.local
            port:
              number: 8080
    - route:
        - destination:
            host: teastore-persistence.user.svc.cluster.local
            port:
              number: 8080