apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence-proxy-cache
  namespace: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore-persistence-proxy-cache
  template:
    metadata:
      labels:
        app: teastore-persistence-proxy-cache
        pattern-managed: "true"
        pattern-type: "cache-aside"
      annotations:
        #instrumentation.opentelemetry.io/inject-python: "otel/otel-operator-instrumentation"
    spec:
      containers:
        - name: flask-proxy
          image: custom-flask-cache-proxy:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SERVICE
              value: "teastore-persistence.user.svc.cluster.local"
            - name: BACKEND_PORT
              value: "8080"
            - name: CACHED_ENDPOINTS
              value: "/tools.descartes.teastore.persistence/rest/products" #/tools.descartes.teastore.persistence/rest/categories,
            - name: REDIS_HOST
              value: "redis-cache-redis-cluster-headless.pattern.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: CACHE_TTL
              value: "300"


# Build image locally
  #docker build -t custom-flask-cache-proxy .

# Load into Minikube
  #minikube image load custom-flask-cache-proxy
# kubectl rollout restart deployment teastore-persistence-proxy-cache -n user