apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: pattern
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: "http, https"
spec:
  rules:
    - http:
        paths: []