apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-service
  namespace: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
        - name: listener-container
          image: listener-service:local
          env:
            - name: SERVICE_URL # recieving message URL
              value: ${SERVICE_URL}
            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
          ports:
            - containerPort: 80
