apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${LISTENER_NAME}
  namespace: user
  labels:
    app: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${LISTENER_NAME}
  template:
    metadata:
      labels:
        app: ${LISTENER_NAME}
      annotations:
        instrumentation.opentelemetry.io/inject-python: "otel/otel-operator-instrumentation"
    spec:
      containers:
        - name: listener-container
          image: listener-service:local
          env:
            - name: BACKEND_SERVICE
              value: "${BACKEND_NAME}"
            - name: BACKEND_PORT
              value: "${BACKEND_PORT}"
            - name: ENDPOINT_PATH
              value: "${ENDPOINT_PATH}"
            - name: RABBITMQ_HOST
              value: "rabbitmq.pattern.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "bitnami"
            - name: REDIS_HOST
              value: "redis-cache.proxy.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 80