apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${LISTENER_NAME}
  namespace: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${LISTENER_NAME}
  template:
    metadata:
      labels:
        app: ${LISTENER_NAME}
    spec:
      containers:
        - name: listener-container
          image: listener-service:local
          env:
            - name: SERVICE_URL
              value: ${SERVICE_NAME} #"http://teastore-auth.user.svc.cluster.local:8080/useractions/login"
            - name: RABBITMQ_HOST
              value: "rabbitmq.pattern.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: QUEUE_NAME
              value: "service-queue"
            - name: EXCHANGE_NAME
              value: "service-exchange"
            - name: ROUTING_KEY
              value: "service-key"
          ports:
            - containerPort: 80