apiVersion: v1
kind: Service
metadata:
  name: ${DB_SERVICE}
  namespace: user
  labels:
    app: proxysql
    tier: frontend
spec:
  type: NodePort
  ports:
    - nodePort: 30036
      port: ${DB_PORT}
      targetPort: ${DB_PORT}
      name: proxysql-mysql
    - nodePort: 30032
      port: 6032
      targetPort: 6032
      name: proxysql-admin
  selector:
    app: proxysql
    tier: frontend