apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: pattern
data:
  # List of endpoints to cache
  CACHED_ENDPOINTS: "/products,/users,/orders"

  # Backend Service (User should set this correctly)
  BACKEND_SERVICE: "teastore-webui.user.svc.cluster.local"
