apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BACKEND_SERVICE}-cache-proxy
  namespace: pattern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${BACKEND_SERVICE}-cache-proxy
  template:
    metadata:
      labels:
        app: ${BACKEND_SERVICE}-cache-proxy
    spec:
      containers:
        - name: nginx
          image: openresty/openresty:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SERVICE
              value: ${BACKEND_SERVICE}
            - name: CACHED_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: ${BACKEND_SERVICE}_CACHED_ENDPOINTS
          volumeMounts:
            - name: nginx-config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-cache-config
---
apiVersion: v1
kind: Service
metadata:
  name: ${BACKEND_SERVICE}-cache-proxy
  namespace: pattern
spec:
  selector:
    app: ${BACKEND_SERVICE}-cache-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort