apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-circuitbreaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-circuitbreaker
  template:
    metadata:
      labels:
        app: envoy-circuitbreaker
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.30-latest
          args:
            - "-c"
            - "/etc/envoy/envoy.yaml"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name:  envoy-circuitbreaker-config #envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-circuitbreaker
spec:
  selector:
    app: envoy-circuitbreaker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
