apiVersion: v1
kind: Service
metadata:
  name: ${BACKEND_SERVICE}
  namespace: user
  labels:
    app: teastore
spec:
  ports:
    - port: ${BACKEND_PORT}
      targetPort: ${BACKEND_PORT}
  selector:
    app: envoy-${BACKEND_SERVICE}
