apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-${BACKEND_SERVICE}
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-${BACKEND_SERVICE}
      run: ${BACKEND_SERVICE}
  template:
    metadata:
      labels:
        app: envoy-${BACKEND_SERVICE}
        run: ${BACKEND_SERVICE}
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.28-latest
          args: ["-c", "/etc/envoy/envoy.yaml"]
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          ports:
            - containerPort: ${BACKEND_PORT}
              name: envoy-port
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config-${BACKEND_SERVICE}