# custom-values.yaml
prometheus:
  service:
    type: NodePort
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'istio-mesh'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_istio_io_rev]
            action: keep
            regex: .+  # Include only Istio-injected pods
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            replacement: /stats/prometheus  # Default metrics path for Istio sidecars
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: (.+):(\d+)
            replacement: $1:15090  # Envoy's metrics port
grafana:
  service:
    type: NodePort
  adminUser: "admin"
  adminPassword: "admin"
  provisioning:
    dashboards:
      enabled: true
      folder: "General"
      files:
        - /etc/grafana/provisioning/dashboards/Kepler-Exporter.json
  extraVolumes:
    - name: dashboard-volume
      configMap:
        name: grafana-dashboard-config
  extraVolumeMounts:
    - name: dashboard-volume
      mountPath: /etc/grafana/provisioning/dashboards
      readOnly: true